package com.hotent.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-11T21:42:14.082+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://iamsweb.gmcc.net/WS/", name = "NotifySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface NotifySoap {

   
    @WebResult(name = "SendSMSExtResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendSMSExt", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendSMSExt")
    @WebMethod(operationName = "SendSMSExt", action = "http://iamsweb.gmcc.net/WS/SendSMSExt")
    @ResponseWrapper(localName = "SendSMSExtResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendSMSExtResponse")
    public com.hotent.wsclient.SendSMSNewResult sendSMSExt(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "toUserID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String toUserID,
        @WebParam(name = "toMobile", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String toMobile,
        @WebParam(name = "fromUserID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String fromUserID,
        @WebParam(name = "fromMobile", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String fromMobile,
        @WebParam(name = "autoForward", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean autoForward,
        @WebParam(name = "validdt", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String validdt,
        @WebParam(name = "allowLock", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean allowLock,
        @WebParam(name = "allowAlert", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean allowAlert,
        @WebParam(name = "sourceNo", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sourceNo,
        @WebParam(name = "content", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String content
    );

   
    @WebResult(name = "SendMessageWithReplyStatusResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendMessageWithReplyStatus", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendMessageWithReplyStatus")
    @WebMethod(operationName = "SendMessageWithReplyStatus", action = "http://iamsweb.gmcc.net/WS/SendMessageWithReplyStatus")
    @ResponseWrapper(localName = "SendMessageWithReplyStatusResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendMessageWithReplyStatusResponse")
    public com.hotent.wsclient.SendMSGResult sendMessageWithReplyStatus(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "smsparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.SmsParms smsparm,
        @WebParam(name = "lcsparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.LcsParms lcsparm,
        @WebParam(name = "emailparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.EmailParms emailparm,
        @WebParam(name = "isreply", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean isreply
    );

   
    @WebResult(name = "SendMessageResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendMessage")
    @WebMethod(operationName = "SendMessage", action = "http://iamsweb.gmcc.net/WS/SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendMessageResponse")
    public com.hotent.wsclient.SendMSGResult sendMessage(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "smsparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.SmsParms smsparm,
        @WebParam(name = "lcsparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.LcsParms lcsparm,
        @WebParam(name = "emailparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.EmailParms emailparm
    );
	
   
    @WebResult(name = "GetSmsStatusSTResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "GetSmsStatusST", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.GetSmsStatusST")
    @WebMethod(operationName = "GetSmsStatusST", action = "http://iamsweb.gmcc.net/WS/GetSmsStatusST")
    @ResponseWrapper(localName = "GetSmsStatusSTResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.GetSmsStatusSTResponse")
    public com.hotent.wsclient.ActionResult getSmsStatusST(
        @WebParam(name = "Sysid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysid,
        @WebParam(name = "SysAccout", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccout,
        @WebParam(name = "Syspwd", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String syspwd,
        @WebParam(name = "smsSendId", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String smsSendId
    );

   
    @WebResult(name = "GetSmsStatusResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "GetSmsStatus", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.GetSmsStatus")
    @WebMethod(operationName = "GetSmsStatus", action = "http://iamsweb.gmcc.net/WS/GetSmsStatus")
    @ResponseWrapper(localName = "GetSmsStatusResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.GetSmsStatusResponse")
    public com.hotent.wsclient.SMSStatusResult getSmsStatus(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "strSmsID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String strSmsID,
        @WebParam(name = "strSubType", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String strSubType
    );

    
    @WebResult(name = "ReceiveMessageResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "ReceiveMessage", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveMessage")
    @WebMethod(operationName = "ReceiveMessage", action = "http://iamsweb.gmcc.net/WS/ReceiveMessage")
    @ResponseWrapper(localName = "ReceiveMessageResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveMessageResponse")
    public com.hotent.wsclient.ReceiveMSGResult receiveMessage(
        @WebParam(name = "strSysID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String strSysID,
        @WebParam(name = "strSysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String strSysAccount,
        @WebParam(name = "strSysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String strSysPassword,
        @WebParam(name = "smsparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.ReceiveSmsParms smsparm,
        @WebParam(name = "lcsparm", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        com.hotent.wsclient.ReceiveLcsParms lcsparm
    );

   
    @WebResult(name = "ReceiveSMSBySJDResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "ReceiveSMSBySJD", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveSMSBySJD")
    @WebMethod(operationName = "ReceiveSMSBySJD", action = "http://iamsweb.gmcc.net/WS/ReceiveSMSBySJD")
    @ResponseWrapper(localName = "ReceiveSMSBySJDResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveSMSBySJDResponse")
    public com.hotent.wsclient.SmsResponse receiveSMSBySJD(
        @WebParam(name = "ServiceNO", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String serviceNO,
        @WebParam(name = "MobileNO", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String mobileNO,
        @WebParam(name = "MessageContent", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String messageContent,
        @WebParam(name = "ReceiveTime", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String receiveTime
    );

   
    @WebResult(name = "SendSMS_FSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendSMS_FS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendSMSFS")
    @WebMethod(operationName = "SendSMS_FS", action = "http://iamsweb.gmcc.net/WS/SendSMS_FS")
    @ResponseWrapper(localName = "SendSMS_FSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendSMSFSResponse")
    public com.hotent.wsclient.SendSMSResult sendSMSFS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "toUserID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String toUserID,
        @WebParam(name = "toMobile", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String toMobile,
        @WebParam(name = "fromUserID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String fromUserID,
        @WebParam(name = "fromMobile", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String fromMobile,
        @WebParam(name = "autoForward", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean autoForward,
        @WebParam(name = "validdt", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String validdt,
        @WebParam(name = "allowLock", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean allowLock,
        @WebParam(name = "allowAlert", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean allowAlert,
        @WebParam(name = "sourceNo", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sourceNo,
        @WebParam(name = "content", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String content,
        @WebParam(name = "isAddId", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String isAddId
    );

   
    @WebResult(name = "CloseReceivedKeywordSMSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "CloseReceivedKeywordSMS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.CloseReceivedKeywordSMS")
    @WebMethod(operationName = "CloseReceivedKeywordSMS", action = "http://iamsweb.gmcc.net/WS/CloseReceivedKeywordSMS")
    @ResponseWrapper(localName = "CloseReceivedKeywordSMSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.CloseReceivedKeywordSMSResponse")
    public com.hotent.wsclient.ActionResult closeReceivedKeywordSMS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "receivedKWsmsid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String receivedKWsmsid
    );

   
    @WebResult(name = "CloseReceivedSMSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "CloseReceivedSMS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.CloseReceivedSMS")
    @WebMethod(operationName = "CloseReceivedSMS", action = "http://iamsweb.gmcc.net/WS/CloseReceivedSMS")
    @ResponseWrapper(localName = "CloseReceivedSMSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.CloseReceivedSMSResponse")
    public com.hotent.wsclient.ActionResult closeReceivedSMS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "receivedSMSID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String receivedSMSID
    );

    
    @WebResult(name = "SendEmail20Result", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendEmail20", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendEmail20")
    @WebMethod(operationName = "SendEmail20", action = "http://iamsweb.gmcc.net/WS/SendEmail20")
    @ResponseWrapper(localName = "SendEmail20Response", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendEmail20Response")
    public com.hotent.wsclient.ActionResult sendEmail20(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "userIDList", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String userIDList,
        @WebParam(name = "emailList", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String emailList,
        @WebParam(name = "subject", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String subject,
        @WebParam(name = "body", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String body,
        @WebParam(name = "AttachmentName", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String attachmentName,
        @WebParam(name = "AttachmentData", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        byte[] attachmentData
    );

   
    @WebResult(name = "ReceiveKeywordSMSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "ReceiveKeywordSMS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveKeywordSMS")
    @WebMethod(operationName = "ReceiveKeywordSMS", action = "http://iamsweb.gmcc.net/WS/ReceiveKeywordSMS")
    @ResponseWrapper(localName = "ReceiveKeywordSMSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveKeywordSMSResponse")
    public com.hotent.wsclient.KWSMSResult receiveKeywordSMS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "keyword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String keyword,
        @WebParam(name = "autoClose", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean autoClose
    );

    
    @WebResult(name = "ReceiveSMSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "ReceiveSMS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveSMS")
    @WebMethod(operationName = "ReceiveSMS", action = "http://iamsweb.gmcc.net/WS/ReceiveSMS")
    @ResponseWrapper(localName = "ReceiveSMSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.ReceiveSMSResponse")
    public com.hotent.wsclient.SMSResult receiveSMS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "autoClose", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean autoClose
    );

    
    @WebResult(name = "SendEmailResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendEmail", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendEmail")
    @WebMethod(operationName = "SendEmail", action = "http://iamsweb.gmcc.net/WS/SendEmail")
    @ResponseWrapper(localName = "SendEmailResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendEmailResponse")
    public com.hotent.wsclient.ActionResult sendEmail(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "userIDList", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String userIDList,
        @WebParam(name = "emailList", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String emailList,
        @WebParam(name = "subject", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String subject,
        @WebParam(name = "body", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String body
    );

    
    @WebResult(name = "SendSMSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendSMS")
    @WebMethod(operationName = "SendSMS", action = "http://iamsweb.gmcc.net/WS/SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.SendSMSResponse")
    public com.hotent.wsclient.SendSMSResult sendSMS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "toUserID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String toUserID,
        @WebParam(name = "toMobile", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String toMobile,
        @WebParam(name = "fromUserID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String fromUserID,
        @WebParam(name = "fromMobile", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String fromMobile,
        @WebParam(name = "autoForward", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean autoForward,
        @WebParam(name = "validdt", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String validdt,
        @WebParam(name = "allowLock", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean allowLock,
        @WebParam(name = "allowAlert", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        boolean allowAlert,
        @WebParam(name = "sourceNo", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sourceNo,
        @WebParam(name = "content", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String content
    );

    
    @WebResult(name = "CancelSMSResult", targetNamespace = "http://iamsweb.gmcc.net/WS/")
    @RequestWrapper(localName = "CancelSMS", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.CancelSMS")
    @WebMethod(operationName = "CancelSMS", action = "http://iamsweb.gmcc.net/WS/CancelSMS")
    @ResponseWrapper(localName = "CancelSMSResponse", targetNamespace = "http://iamsweb.gmcc.net/WS/", className = "com.hotent.wsclient.CancelSMSResponse")
    public com.hotent.wsclient.ActionResult cancelSMS(
        @WebParam(name = "systemid", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String systemid,
        @WebParam(name = "sysAccount", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysAccount,
        @WebParam(name = "sysPassword", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sysPassword,
        @WebParam(name = "sendSMSID", targetNamespace = "http://iamsweb.gmcc.net/WS/")
        java.lang.String sendSMSID
    );
}
