package com.hotent.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-11T21:42:14.252+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "Notify", 
                  wsdlLocation = "file:/d:/lhxc1.wsdl",
                  targetNamespace = "http://iamsweb.gmcc.net/WS/") 
public class Notify extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://iamsweb.gmcc.net/WS/", "Notify");
    public final static QName NotifySoap12 = new QName("http://iamsweb.gmcc.net/WS/", "NotifySoap12");
    public final static QName NotifySoap = new QName("http://iamsweb.gmcc.net/WS/", "NotifySoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/lhxc1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Notify.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/lhxc1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Notify(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Notify(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Notify() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /*
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Notify(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Notify(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Notify(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    
	*/
    /**
     *
     * @return
     *     returns NotifySoap
     */
    @WebEndpoint(name = "NotifySoap12")
    public NotifySoap getNotifySoap12() {
        return super.getPort(NotifySoap12, NotifySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotifySoap
     */
    @WebEndpoint(name = "NotifySoap12")
    public NotifySoap getNotifySoap12(WebServiceFeature... features) {
        return super.getPort(NotifySoap12, NotifySoap.class, features);
    }
    /**
     *
     * @return
     *     returns NotifySoap
     */
    @WebEndpoint(name = "NotifySoap")
    public NotifySoap getNotifySoap() {
        return super.getPort(NotifySoap, NotifySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotifySoap
     */
    @WebEndpoint(name = "NotifySoap")
    public NotifySoap getNotifySoap(WebServiceFeature... features) {
        return super.getPort(NotifySoap, NotifySoap.class, features);
    }

}
